### ISSUE TITLE
ask for some details

### ISSUE THREAD

**Issue by Lawriegan** [TengdaHan/cpc_video#2]
I'm also interested in the idea about cpc2video when I read this paper. Are you still working on it? I noticed the Known Problems part in your Readme file, could you please explain the meaning of " while for videos, network can easily cheat by keeping the 'flow' among video frames to predict near future."? 
Thanks a lot !

**Comment by TengdaHan** [comment]
See the [paper](https://arxiv.org/pdf/1807.03748.pdf) figure 3: for near future (like step 1, 2), accuracy is high, but for far future (step 4+), accuracy drops quickly. This is expected, because for near future, network can simply learn to extend the optical flow from input sequence, and get a low loss for near future. But what people want the network to learn, is the semantic of the video, not just flow info. 

We're working on how to avoid learning this shortcut.

**Comment by Lawriegan** [comment]
Thanks! Looking forward to your progress.
